### ISSUE TITLE
Disagreement with one statement

### ISSUE THREAD

**Issue by timmens** [EdwinTh/ADSwR#25]
I really enjoyed reading your book! Especially the term *code overfitting*, which I haven't heard before, I will certainly adopt in my technical vocabulary.

One statement that I thought of as out of place is in your introduction to chapter 7:

> [...] R is designed with interactivity in mind, it enables the user to have a direct Q&A with the data.
> **This is an unparalleled feature of the R language, making it uniquely suitable for drawing quick insights and conclusions from data.**

I guess there were times where this statement was true; however, I believe you also know that nowadays interactive programming can be done with various tools and languages. For the sake of concreteness consider MATLAB, Python combined with jupyter notebooks or the ipython shell,  or Julia and Scala which can also be run on jupyter notebooks.

Feel free to close the issue if you don't agree or if I misunderstood you. This is simply meant to draw attention to a sentence that I thought of as out of place considering the rest of the book.

Best regards, Tim

**Comment by EdwinTh** [comment]
Hi Tim,

Thanks for your comment. I am fully aware that this is highly subjective, but I guess that is why I call it an opinionated view. Personally, I have not experienced a language that was as good for data Q&A as R in combination with Rstudio. To me the sheer fact that in jupyter notebooks you are required to run an entire cell and cannot quickly check the value belonging to a variable (and not have a repl to quickly test things) are already breaking my flow. Although it came a long way, to me, it is not as good as R. I'll fully admit that I have no experience using MATLAB, but since this is an open source book I consider the open source world.

Thanks again for mentioning and for reading the book!
Edwin
